#!/bin/bash
# Dynamic startup script for distributed simulation
# Generates docker-compose configuration with specified number of nodes

set -e

# Default values
NODE_COUNT=${1:-5}
TOPOLOGY=${2:-RING}
COMPOSE_FILE="docker-compose-distributed-generated.yml"

# Validate input
if ! [[ "$NODE_COUNT" =~ ^[0-9]+$ ]] || [ "$NODE_COUNT" -lt 1 ]; then
    echo "Error: NODE_COUNT must be a positive integer"
    echo "Usage: $0 <node_count> [topology]"
    echo "Example: $0 10 RING"
    exit 1
fi

echo "=================================================="
echo "  Distributed System Startup"
echo "=================================================="
echo "Node Count: $NODE_COUNT"
echo "Topology:   $TOPOLOGY"
echo "Config:     $COMPOSE_FILE"
echo ""

# Generate docker-compose.yml
cat > "$COMPOSE_FILE" << 'EOF'
version: '3.8'

# Auto-generated docker-compose for distributed simulation
# Generated by start-distributed.sh

services:
  # Backend API server
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vsp-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MW_MODE=virtual
      - DISTRIBUTED_MODE=true
EOF

echo "      - DISTRIBUTED_NODE_COUNT=$NODE_COUNT" >> "$COMPOSE_FILE"
echo "      - DISTRIBUTED_TOPOLOGY=$TOPOLOGY" >> "$COMPOSE_FILE"

cat >> "$COMPOSE_FILE" << 'EOF'
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - vsp-network

EOF

# Generate node services
for i in $(seq 0 $(($NODE_COUNT - 1))); do
    cat >> "$COMPOSE_FILE" << EOF
  # Simulation Node $i
  node-$i:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: vsp-node-$i
    hostname: node-$i
    environment:
      - MW_MODE=udp-docker
      - NODE_ID=node-$i
      - UDP_PORT=9000
      - HOST_TEMPLATE={ID}
      - NODE_COUNT=$NODE_COUNT
      - TOPOLOGY=$TOPOLOGY
    networks:
      - vsp-network
    depends_on:
      - backend

EOF
done

# Add network configuration
cat >> "$COMPOSE_FILE" << 'EOF'
networks:
  vsp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16
EOF

echo "✓ Generated $COMPOSE_FILE with $NODE_COUNT nodes"
echo ""
echo "Starting containers..."
echo ""

# Start the system
docker-compose -f "$COMPOSE_FILE" up --build "$@"
